### ISSUE TITLE
State 값이 정상적으로 전송되지 않는 문제

### ISSUE THREAD

**Issue by midlife** [YJSoft/xe-module-loginxeserver#3]
네이버 로그인 연동이 안되고 잘못된 요청이라는 메시지만 뜹니다.
index.php?module=loginxeserver&act=dispLoginxeserverOAuthFinish&provider=naver&code=IbiDbHgRbcdoNLt1&state=(null)
ftp로 다시 xe클라이언트, xe서버 재 업로드해서 해봐도 마찬가지이구요.
제 서버정보 같이 올립니다. 한번 봐주세요.

[XE Server Environment 2015-03-29]

location : ko
package : XE
app : Apache
xe_version : 1.7.12
php : 5.5.17p1
db_type : mysql
use_rewrite : Y
use_db_session : N
use_ssl : optional
phpext : core, ereg, libxml, openssl, sqlite3, zlib, bcmath, bz2, curl, dba, fileinfo, ftp, gd, gettext, iconv, mbstring, mcrypt, pdo_sqlite, phar, simplexml, sockets, exif, sysvmsg, sysvsem, sysvshm, xml, xmlreader, xmlrpc, xmlwriter, zip, apache, mysql, mysqli, oci8, pgsql, mssql, cubrid, pdo_mysql, soap, memcache, redis, mhash, ioncube loader
module : adminlogging(1.7), board(1.7.2), board_extend(1.1), bulkmsg(1.0), checkip(0.2.2), contact(1.7.0.2), coupon(1.0), faq(1.7.0.1), forum(1.7.0.1), homepage(1.7.0.1), isx(1.7.4.1), kin(1.7.0), krzip(1.8.0), loginlog(0.5.1), loginxeclient(1.05), loginxeserver(1.04), lottery(0.1), marketplace(1.3), material(1.0), msg_admin(0.1), ncenterlite(2.1.3), quizgame(0.1), realnotice(0.5), referer(3.8.2), rockgame(0.4), sejin7940_nick(1.0.2), sitemap(1.2), syndication(4.0), textyle(1.7.0), textylehub(1.7.0), timeline(1.0.1), xewall(0.3.1), ximember(1.4), zzz_menu_new(1.7.0)
addon : aa_insert_ad(1.0.0), activescrollbar(1.0), addon_insert_sticker(0.1), addvote(1.0), adminlogging(1.7), age_restrictions(1.0), appoint_view_user(1.0), auto_nick(1.0), block_control(1.0), bootstrap_icon(1.1), cameron_plugin(1.2), captcha_member(1.7), change_nickname(2.0), doc_viewer(0.1.2), falling_snow3(1.0.0), googleplus(0.1.1), gosite(0.1), hidden_module(0.3), hot_document(1.2.2), html5multimedia_flash(1.0.0), html5video_flash(1.0.0), iframe_resize(0.2), image_preview(1.0), layerpopup(1.10), limit_message(0.2), login_defencer(1.0), member_block_addon(0.4), member_join_ex(0.2.3), memberinfo(1.10), meta_add(0.2.2), msg_point(1.0), multimedia_thumbnail(2.0.0), new_document_notify(2.0), noclick(1.3), oembed(1.0), point_pang_pang(1.1), qrcode(0.2), referer(3.4.1), scmplayer(1.5), sejin7940_all_notice(1.4), sejin7940_autotrash(1.1.1), sejin7940_kakao_link(0.5.3), sejin7940_mustlogin(0.2), sejin7940_readed_count(1.6), sex_restrictions(0.1.1), sns_linker_lite(1.1), soo_add_content(0.5), source_marking(0.3), stop_spambot_xe(0.6), xdt_button(1.0), xdt_scrollbar(1.0), xss_session_protector(0.1), youtube_control(1.2)
layout : xe_cafe_site(1.7.0), xe_cafe_hub(1.7.0), cafeXE(1.7.0), xe_cafe(1.7.0), xe_official(1.7), user_layout(1.7)
widget : bannerWidget(0.3), calendar(0.2), cameronSlider(1.0.2), category(0.1), counter_status(1.7), forum(0.1), gagachat(3.7), ggboardinsert_widget(0.8), ideationBanner(0.1), lineadWidget(0.8), logged_members(0.1), login_sunoo(1.0), member_group(0.1), navigator(1.7.0), newest_document(1.0), newest_trackback(0.1), nkoclock(0.1), notice(1.0.4), padoLittleBanner(0.1), rank_count(1.5), site_info(1.7.0), slideimg(1.1.2), tab_newest_document(0.1), tag_list(0.1), treasurej_popular(1.0.5)
widgetstyle : simple(1.7)
max_file_uploads : 20
post_max_size : 21M
memory_limit : 128M

**Comment by YJSoft** [comment]
@midlife 확인해 보도록 하겠습니다.

**Comment by YJSoft** [comment]
@midlife 매뉴얼( http://server.loginxe.cf/ )을 참고해서 도메인 설정을 완료하신뒤 확인해 보세요.
현재 state는 정상적으로 생성되고, 전달되고 있습니다.
